### ISSUE TITLE
Reopen of #35

### ISSUE THREAD

**Issue by Jovin-Ang** [gazmull/discord-paginationembed#36]
I am still running into this issue, reference to #35 
```
TypeError: Cannot read property 'last' of undefined
    at exports.Embeds._awaitResponse (/rbd/pnpm-volume/62876d80-160e-479c-88ac-d013b13a516d/node_modules/.registry.npmjs.org/discord-paginationembed/2.0.0-beta.4/node_modules/discord-paginationembed/bin/base/index.js:163:38)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by Jovin-Ang** [comment]
Just a simple test code like this:
```js
const embeds = [];
      
      embeds.push(
        new Discord.MessageEmbed()
        .setDescription("hello")
      );
      embeds.push(
        new Discord.MessageEmbed()
        .setDescription("yo yo yo")
      );
      
      // Send the embed
      const Embeds = new Pagination.Embeds()
        .setArray(embeds)
        .setAuthorizedUsers([message.author.id])
        .setChannel(message.channel)
        .setPageIndicator(true)
         // Methods below are for customising all embeds
        .setFooter("navigate between pages using ◀▶ • Last updated", this.client.user.displayAvatarURL({ size: 2048 }).replace(".webp",".png"))
        .setTimestamp()
        .setColor(0xF19F00)
        //.build()
      // Upon non-PaginationEmbed error (e.g: Discord API Error)
  .on('error', console.error);
      
      await Embeds.build();```

**Comment by gazmull** [comment]
This shouldn't occur with Discord.JS master commit later than or equivalent to [`bbdbc4c`](https://github.com/discordjs/discord.js/commit/bbdbc4cfa789383b7b3dbecf5e6b8401ea2dd998). Please check your Discord.JS installation.

**Comment by Jovin-Ang** [comment]
I just updated my discord.js to the latest commit and it solved the issue.
Terribly sorry for not checking discord.js first before opening this issue.
