### ISSUE TITLE
this.clientAssets.prompt.replace is not a function

### ISSUE THREAD

**Issue by vyvu99** [gazmull/discord-paginationembed#63]
```
(node:16116) UnhandledPromiseRejectionWarning: TypeError: this.clientAssets.prompt.replace is not a function
    at exports.Embeds._awaitResponseEx (\node_modules\discord-paginationembed\bin\base\index.js:206:89)
    at exports.Embeds._awaitResponse (\node_modules\discord-paginationembed\bin\base\index.js:173:63)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:16116) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4) 
```
appears when I use page jumper

**Comment by vyvu99** [comment]
oh, I found it, my "prompt" property is an object, it needs to be a string
